# Generated by Django 4.2.2 on 2023-06-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='energy',
            name='updated_at',
        ),
    ]
